name: CI

on:
  push:
    branches: [pl-wcag-22-nowe]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build pages
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Java
        # see https://github.com/actions/setup-java#supported-distributions
        # note that this also deploys ant
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: before_install
        run: |
          tar -xzvf lib/apache-ant-1.10.6-bin.tar.gz
          echo "$(pwd)/apache-ant-1.10.6/bin" >> $GITHUB_PATH

      - name: script
        run: |
          mkdir -p \
                output/guidelines/22 \
                output/requirements/22 \
                output/conformance-challenges

          curl -f --retry 3 \
            "https://www.w3.org/publications/spec-generator/?type=respec&url=https://raw.githack.com/irdpl/wcag/pl-wcag-22-nowe/guidelines/index.html" \
            -o output/guidelines/22/index.html

          curl -f --retry 3 \
            "https://www.w3.org/publications/spec-generator/?type=respec&url=https://raw.githack.com/irdpl/wcag/pl-wcag-22-nowe/requirements/22/index.html" \
            -o output/requirements/22/index.html

          curl -f --retry 3 \
            "https://www.w3.org/publications/spec-generator/?type=respec&url=https://raw.githack.com/irdpl/wcag/pl-wcag-22-nowe/conformance-challenges/index.html" \
            -o output/conformance-challenges/index.html

          ant deploy

      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-artifact
          path: |
            ./output

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
