name: CI

# Reference documentation: https://docs.github.com/en/actions/reference

# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    branches: [pl-wcag-22-nowe]
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  main:
    name: deploy
    runs-on: ubuntu-20.04
    env:
      GH_REF: github.com/irdpl/wcag.git
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Java
        # see https://github.com/actions/setup-java#supported-distributions
        # note that this also deploys ant
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: before_install
        run: |
          tar -xzvf lib/apache-ant-1.10.6-bin.tar.gz
          export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
      - name: script
        run: |
          mkdir output
          git clone --depth=1 --branch=gh-pages https://github.com/irdpl/wcag.git output
          curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/irdpl/wcag/pl-wcag-22-nowe/guidelines/index.html -o output/guidelines/22/index.html -f  --retry 3
          curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/irdpl/wcag/pl-wcag-22-nowe/requirements/22/index.html -o output/requirements/22/index.html -f  --retry 3
          curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/irdpl/wcag/pl-wcag-22-nowe/conformance-challenges/index.html -o output/conformance-challenges/index.html -f  --retry 3
          ant deploy

      - name: Upload Artifact
        if: failure()  # Upload artifact only if the previous step (Build) fails
        uses: actions/upload-artifact@v4
        with:
          name: failed-artifact
          path: |
                ./
                !output

      - name: deploy
        run: .github/scripts/deploy.sh
        env:
          BRANCH: gh-pages
          LOCAL_DIR: output
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

